#!/usr/bin/python

import sys

from gui.dialog_boost.MainDialogBoost import Boost
from PyQt5.QtWidgets import QApplication

application = QApplication(sys.argv)

boost = Boost()
boost.show()

sys.exit(application.exec_())
