#!/usr/bin/python

import sys

from PyQt5.QtWidgets import QApplication

from gui.dialog_boost.MainDialogBoost import Boost

if __name__ == "__main__":
    application = QApplication(sys.argv)

    boost = Boost()
    boost.show()

    sys.exit(application.exec_())
